name: cached_gif
description: Forked project with control a gif using flutter animation controller. You can either specify a fixed duration or set the framerate of the playback.
version: 2.4.0
homepage: https://github.com/Darkildo/flutter_gif

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

flutter:
