name: gif
description: Fork of flutter_gifimage that uses standard animation controllers
version: 1.0.1
homepage: https://github.com/pierluigizagaria/flutter_gif

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:

